# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_publishing', '0002_versionpermissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionpermissions',
            name='visibility_permission',
        ),
        migrations.AddField(
            model_name='versionpermissions',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Authenticated'), (2, 'Workgroup')], default=2),
        ),
    ]
