# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_publishing', '0005_auto_20190524_1245'),
        ('aristotle_mdr_publishing', '0005_auto_20190529_1048'),
    ]

    operations = [
    ]
