# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-08 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0016_auto_20190801_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkdimension',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='frameworkdimension',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='frameworkdimension',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
