version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379"

  db:
    image: postgres
    volumes:
      - ../../../data/db/:/var/lib/postgresql/data

  elasticsearch:
    # If elasticsearch won't boot, you need to run `sudo sysctl -w vm.max_map_count=262144`
    # On your host machine
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    container_name: elasticsearch-mdr
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 1g
    deploy:
      resources:
        limits:
          # cpus: '0.50'
          memory: 1024M
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


  web:
    <<: &django 
      build:
        context: ..
        dockerfile: docker/Dockerfile.dev
      image: aristotle_metadata_registry:dev
      environment:
        - DATABASE_URL=postgresql://postgres:@db:5432/postgres
        - DJANGO_SETTINGS_MODULE=settings
        - PYTHONPATH=.
        - DJANGO_DEBUG=True
      depends_on:
        - db
        - redis
        - elasticsearch
    command: sh ./sh/entrypoint/web.sh
    ports:
      - "8080:8000"
    volumes:
        - ../:/usr/src/app
        - ../../../data:/data

  worker:
    <<: *django
    command: sh ./docker/sh/entrypoint/worker.sh
    links:
      - redis
    volumes:
        - ../:/usr/src/app

volumes:
  esdata1:
    driver: local
