version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379"
    volumes:
      - cache_data:/data

  db:
    image: postgres:10
    volumes:
      - db_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8082:8025"
      - "1025:1025"

  elasticsearch:
    # If elasticsearch won't boot, you need to run `sudo sysctl -w vm.max_map_count=262144`
    # On your host machine
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    container_name: elasticsearch-mdr
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 1g
    deploy:
      resources:
        limits:
          # cpus: '0.50'
          memory: 1024M
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


  web:
    <<: &django 
      build:
        context: ..
        dockerfile: docker/Dockerfile.dev
      image: aristotle_metadata_registry:dev
      environment:
        - GRAPHQL_ENABLED=True
        - DATABASE_URL=postgresql://postgres:@db:5432/postgres
        - DJANGO_SETTINGS_MODULE=settings
        - PYTHONPATH=.
        - DJANGO_DEBUG=True
        - aristotlemdr__FILE_VALIDATION_RUNNER_PATH=/usr/src/app/docker/examples/validation_rules/base.yaml
      depends_on:
        - db
        - redis
        - elasticsearch
    command: sh ./sh/entrypoint/web.sh
    ports:
      - "8000:8000"
    volumes:
        - ../:/usr/src/app
        - ../../../data:/data

  webpack:
    tty: false
    working_dir: /usr/src/app/aristotle-metadata-registry/assets
    image: node:8.12
    command: npm run installandwatch
    volumes:
        - ../../:/usr/src/app

  worker:
    <<: *django
    command: sh ./sh/entrypoint/worker.sh
    environment:
      - DATABASE_URL=postgresql://postgres:@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=settings
      - PYTHONPATH=.
      - DJANGO_DEBUG=False
    links:
      - redis
    volumes:
        - ../:/usr/src/app

volumes:
  es_data:
    driver: local
  cache_data:
    driver: local
  db_data:
    driver: local
