# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 09:54
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0063_auto_20190515_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='_concept',
            name='_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='possumprofile',
            name='profilePicture',
            field=aristotle_mdr.fields.ConvertedConstrainedImageField(blank=True, content_types=['image/jpg', 'image/png', 'image/bmp', 'image/jpeg', 'image/x-ms-bmp'], height_field='profilePictureHeight', js_checker=True, max_upload_size=10485760, mime_lookup_length=4096, null=True, upload_to='', width_field='profilePictureWidth'),
        ),
        migrations.AlterField(
            model_name='supersederelationship',
            name='proposed',
            field=models.BooleanField(default=False, help_text='Whether this is a proposal or an active supersedes relation'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_mdr.Measure'),
        ),
        migrations.AlterField(
            model_name='valuedomain',
            name='classification_scheme',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valueDomains', to='aristotle_mdr_backwards.ClassificationScheme', verbose_name='Classification Scheme'),
        ),
        migrations.AlterField(
            model_name='valuedomain',
            name='conceptual_domain',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, help_text='The Conceptual Domain that this Value Domain which provides representation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_mdr.ConceptualDomain', verbose_name='Conceptual Domain'),
        ),
        migrations.AlterField(
            model_name='valuedomain',
            name='data_type',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, help_text='Datatype used in a Value Domain', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_mdr.DataType', verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='valuedomain',
            name='representation_class',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_domains', to='aristotle_mdr_backwards.RepresentationClass', verbose_name='Representation Class'),
        ),
        migrations.AlterField(
            model_name='valuedomain',
            name='unit_of_measure',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, help_text='Unit of Measure used in a Value Domain', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_mdr.UnitOfMeasure', verbose_name='Unit Of Measure'),
        ),
    ]
