# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0067_auto_20190605_1538'),
        ('aristotle_mdr', '0065_auto_20190524_1245'),
    ]

    operations = [
    ]
