# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-08 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0069_auto_20190801_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='registrationDate',
            new_name='effective_date',
        ),
    ]
