# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 04:17
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_review_requests', '0001_squashed_0005_initial_squashed'),
        ('aristotle_mdr_backwards', '0001_squashed_0004_squish'),
        ('aristotle_mdr', '0001_squashed_0072__v310_squishy_part1'),
    ]
    replaces = [
        ('aristotle_mdr', '0073_auto_20190814_1520'),
        ('aristotle_mdr', '0074_auto_20190908_0648'),
        ('aristotle_mdr', '0075_auto_20190916_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersederelationship',
            name='review',
            field=aristotle_mdr.fields.ConceptForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='aristotle_mdr_review_requests.ReviewRequest'),
        ),
        migrations.AddField(
            model_name='valuedomain',
            name='representation_class',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True,
                                                         on_delete=django.db.models.deletion.SET_NULL,
                                                         related_name='value_domains',
                                                         to='aristotle_mdr_backwards.RepresentationClass',
                                                         verbose_name='Representation Class'),
        ),
        migrations.AddField(
            model_name='valuedomain',
            name='classification_scheme',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True,
                                                         on_delete=django.db.models.deletion.SET_NULL,
                                                         related_name='valueDomains',
                                                         to='aristotle_mdr_backwards.ClassificationScheme',
                                                         verbose_name='Classification Scheme'),
        ),
    ]
