# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-12 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0072_auto_20190809_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissiblevalue',
            options={'ordering': ['order'], 'verbose_name': 'Permissible Value'},
        ),
        migrations.AlterModelOptions(
            name='supplementaryvalue',
            options={'ordering': ['order'], 'verbose_name': 'Supplementary Value'},
        ),
        migrations.RenameField(
            model_name='status',
            old_name='registrationDate',
            new_name='effective_date',
        ),
    ]
