# Generated by Django 2.2.4 on 2019-08-19 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0073_auto_20190814_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='registrationDate',
            new_name='effective_date',
        ),
    ]
