name: Accessibility Tests
on:
  pull_request:
    paths:
      - 'python/**'
      - 'Pipfile.lock'
      - 'Pipfile'
      - '.github/workflows/python.yaml' # Run on every change to itself
  push:
    branches:
      - master
      - develop

jobs:
  name: 'Accessibility Testing'
  strategy:
    matrix:
      accessibility_test:
        - 'Metadata Item'
        - 'Metadata Action'
        - 'Static'

      include:
        - accessibility_test: 'Metadata Item'
          ALLY: 'metadata_item'
        - accessibility_test: 'Metadata Action'
          ALLY: 'metadata_action'
        - accessibility_test: 'Static'
          ALLY: 'static'
  env:
    DATABASE_URL: postgresql://postgres:postgres@localhost:5432/aristotle_db
    MODULE: 'aristotle-metadata-registry'

  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1

  - uses: actions/setup-python@v1

  - uses: actions/setup-node@v1
    with:
      node-version: 10.x

  - name: Install Python dependencies
    run: |
      pip install codecov coveralls
      pip install 'tox>=3.0'
      nvm install 10.13.0

  - name: Install npm dependencies
    run: |
      set -ev
      cd ./assets
      npm install
      npm run devbuild

  - name: Run accessibility tests
    run: tox -e dj-linux-ally-${{ matrix.ALLY }}-module_amr
    env:
      MODULE: ${{ matrix.MODULE }}

  services:
    postgres:
      image: postgres:10.10
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: aristotle_db
      ports:
        - 5432:5432



