name: JavaScript Linting
on:
  pull_request:
    paths:
      - '**.js'
      - '**.vue'

jobs:
  js_lint:
      name: Javascript Lint
      runs-on: ubuntu-latest
      steps:
        - uses: 'actions/checkout@v1'
        - name: Setup node
          uses: 'actions/setup-node@v1'
          with:
            node-version: 10
        - name: Install dependancies
          run: |
            cd assets
            npm install
        - name: Lint
          run: |
            cd assets
            npm run lint
