name: Main Python Tests
on: [pull_request]

jobs:
  main_testing:
    strategy:
      matrix:
        python_module: [amr, dse, cir, gql, api, bgw]

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost/aristotle_db
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: actions/setup-python@v1

    - name: Install tox
      run: pip install "tox>=3.0"

    - name: Run tests
      run: tox -e dj-test-linux-db-postgres-search-elastic-module${{ matrix.python_module }}

    services:
      postgres:
        image: postgres:10.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aristotle_db
        ports:
          - 5432/tcp # Will assign a random free port in reality
        options:
          # Health check to double check when it's ready
          "--health-cmd pg_isready --health-interval 10s --health-timeout 5s --health retires"

      redis:
        image: redis:latest

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
        ports:
        - 9200/tcp



