name: Python Linting
on:
  pull_request:
    paths:
      - '../../aristotle-metadata-registry/python/*'

jobs:
  python_lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/checkout@v1
      - name: Install flake8
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
        run: pip install flake8
      - name: Lint
        run: flake8
  python_typing:
    name: Python type checking
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/checkout@v1
      - name: Install mypy
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
        run: pip install mypy
      - name: Type checking
        shell: bash
        run: |
          mypy $(find ./python/ -maxdepth 3 -name '__init__.py' -printf '%h\n')
