name: Main Python Tests
on:
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/python.yaml' # Run on every change to itself

jobs:
  python-lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v1
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install flake8
        run: pip install flake8
      - name: Lint
        run: flake8

  python-typing:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v1
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install mypy
        run: pip install mypy
      - name: Type checking
        shell: bash
        run: |
          mypy $(find ./python/ -maxdepth 3 -name '__init__.py' -printf '%h\n')

  main_testing:
    name: Main Testing
    strategy:
      matrix:
        python_module: [amr, dse, cir, gql, api]

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/aristotle_db
      SEARCH: elastic

    runs-on: ubuntu-latest

    steps:
    - name: Restart elasticsearch
      run: |
        sudo sysctl -w vm.max_map_count=262144
        docker restart $(docker ps -a -q
        docker ps
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: actions/setup-python@v1

    - name: Install tox
      run: pip install "tox>=3.0"

    - name: Install npm dependencies
      run: |
        set -ev
        cd ./assets
        npm install
        npm run devbuild

    - name: Install postgres dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpq-dev -y

    - name: Run tests
      run: tox -e dj-test-linux-db-postgres-search-elastic-module_${{ matrix.python_module }}

    services:
      postgres:
        image: postgres:10.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aristotle_db
        ports:
          - 5432:5432
      redis:
        image: redis:latest

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
        ports:
          - 9200:9200