name: Python
on:
  pull_request:
    paths:
      - 'python/**'

jobs:
  python-lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v1
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install flake8
        run: pip install flake8
      - name: Lint
        run: flake8
  python-typing:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v1
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install mypy
        run: pip install mypy
      - name: Type checking
        shell: bash
        run: |
          mypy $(find ./python/ -maxdepth 3 -name '__init__.py' -printf '%h\n')
